In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [9]:
df = pd.read_csv("/content/hiring.csv",names=["experience","test_score","interview_score","salary"],skiprows=1)
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [10]:
nan_value=df.test_score.median()
df.test_score= df.test_score.fillna(nan_value)
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [11]:
!pip install word2number

  Created wheel for word2number: filename=word2number-1.1-cp37-none-any.whl size=5584 sha256=f10bea1487cc924edd585663deb319dd56f08c84bebf647b442d3a3a080c50f2
  Stored in directory: /root/.cache/pip/wheels/46/2f/53/5f5c1d275492f2fce1cdab9a9bb12d49286dead829a4078e0e
Successfully built word2number


In [12]:
df.experience=df.experience.fillna("zero")
df

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [22]:
w2n={'zero':0,'one':1,'two':2,'three':3,'four':4,'five':5,'six':6,'seven':7,'eight':8,'nine':9,'ten':10,'eleven':11}
df.experience[7]=w2n[df.experience[7]]
df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


experience  test_score  interview_score  salary
0          0         8.0                9   50000
1          0         8.0                6   45000
2          5         6.0                7   60000
3          2        10.0               10   65000
4          7         9.0                6   70000
5          3         7.0               10   62000
6         10         8.0                7   72000
7         11         7.0                8   80000

In [23]:
reg=linear_model.LinearRegression()
reg.fit(df[["experience","test_score","interview_score"]],df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [24]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [25]:
reg.intercept_

17737.263464337702

In [26]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [27]:
reg.predict([[12,10,10]])

array([92002.18340611])